'use strict';
module.exports = (sequelize, DataTypes) => {
  var Chat = sequelize.define('Chat', {
    name: {
      required: true,
      type: DataTypes.STRING,
      default: "Channel-Name"
    },
    UserId: {
      required: true,
      type: DataTypes.INTEGER
    }
  }, {
  	timestamps: true
  });
  Chat.associate = function(models) {
    // associations can be defined here
    Chat.belongsToMany(models.User, {
    	as: 'Users',
    	through: 'UserChats',
    	foreignKey: 'ChatId',
    	otherKey: 'UserId'
    });

    Chat.hasMany(models.Message, {
    	as: 'Messages', //this is what provides the autogenerated instance methods of getMessages|setMessage, etc.
    	foreignKey: 'to'
    })
  };
  return Chat;
};